# permissions for end users to edit kubesprayjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesprayjob-editor-role
rules:
- apiGroups:
  - cluster.wanglet.com
  resources:
  - kubesprayjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.wanglet.com
  resources:
  - kubesprayjobs/status
  verbs:
  - get
