# permissions for end users to view kubesprayjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesprayjob-viewer-role
rules:
- apiGroups:
  - cluster.wanglet.com
  resources:
  - kubesprayjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.wanglet.com
  resources:
  - kubesprayjobs/status
  verbs:
  - get
